// Notes:
// single color after its compound colors

const colorList = [
  'abricot',
  'argent',
  'assorti',
  'beige',
  'blanc',
  'bleu ciel',
  'bleu clair',
  'bleu fluo',
  'bleu foncé',
  'bleu indigo',
  'bleu métallique',
  'bleu nacré',
  'bleu pailleté',
  'bleu pâle',
  'bleu nuit',
  'bleu océan',
  'bleu royal',
  'bleu vif',
  'bleu',
  'bordeau',
  'bronze',
  'brun clair',
  'brun foncé',
  'brun',
  'canari',
  'cerise',
  'chair',
  'chamois',
  'charcoal',
  'clémentine',
  'cramoisi',
  'crème',
  'cyan',
  'écarlate',
  'framboise',
  'fushia',
  'gris',
  'ivoire',
  'jasmin',
  'jaune citron',
  'jaune clair',
  'jaune doré',
  'jaune fluo',
  'jaune foncé',
  'jaune métallique',
  'jaune orange',
  'jaune pailleté',
  'jaune paille',
  'jaune pâle',
  'jaune soleil',
  'jaune vif',
  'jaune',
  'citron',
  'kaki',
  'lavande',
  'lilas',
  'magenta',
  'marron',
  'mauve clair',
  'mauve fluo',
  'mauve foncé',
  'mauve métallique',
  'mauve pailleté',
  'mauve pâle',
  'mauve vif',
  'mauve',
  'noir',
  'or pailleté',
  'or ',
  'orange clair',
  'orange fluo',
  'orange foncé',
  'orange métallique',
  'orange pailleté',
  'orange pâle',
  'orange vif',
  'orange',
  'pêche',
  'pistache',
  'rose clair',
  'rose fluo',
  'rose foncé',
  'rose métallique',
  'rose nacré',
  'rose pailleté',
  'rose pâle',
  'rose vif',
  'rose',
  'rouge carmin',
  'rouge clair',
  'rouge métallique',
  'rouge fluo',
  'rouge foncé',
  'rouge pailleté',
  'rouge pâle',
  'rouge pavot',
  'rouge vif',
  'rouge',
  'saumon',
  'sienne',
  'tan cashemire',
  'turquoise',
  'vermil clair',
  'vermil',
  'vert antique',
  'vert clair',
  'vert émeraude',
  'vert fluo',
  'vert foncé',
  'vert forêt',
  'vert lagon',
  'vert lime',
  'vert menthe',
  'vert métallique',
  'vert mousse',
  'vert olive',
  'vert pailleté',
  'vert pâle',
  'vert pomme',
  'vert pré',
  'vert sapin',
  'vert vif',
  'vert',
  'violet clair',
  'violet fluo',
  'violet foncé',
  'violet métallique',
  'violet pailleté',
  'violet pâle',
  'violet vif',
  'violet',
];

module.exports = colorList;
