const pencilTipList = [
  'aquarelle',
  'cire',
  'crayon de bois',
  'crayons de bois',
  'crayon bois',
  'crayons bois',
  'crayon de croquis',
  'crayons de croquis',
  'crayon croquis',
  'crayons croquis',
  'crayon de couleur',
  'crayons de couleur',
  'crayon coul',
  'crayons coul',
  'crayon à colorier',
  'crayons à colorier',
  'crayon mine',
  'crayons mine',
  'fusain',
  'pastel',
  'portemine',
  'porte-mine',
  'p-mine',
  'p.-mine',
  'prisma',
];

module.exports = pencilTipList;
